baseURL = "https://J0SE-ESC0BAR.github.io/"
languageCode = 'es'
title = "JAEM"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "@JAEM_Developer"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = false
# agregar mas entradas a la cabezera
#[menu]
#  [[menu.main]]
#    identifier = "contacto1"
#    name = "Contacto1"
#    title = "contacto1"
#    url = "/contacto1/"
#    weight = 0
#  [[menu.main]]
#    identifier = "contacto2"
#    name = "Contacto2"
#    title = "contacto2"
#    url = "/contacto2/"
#    weight = 0